# Generated by Django 4.1.1 on 2023-04-19 15:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_fedbacktoboo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FedbackToBoo',
            new_name='FedbackToBook',
        ),
    ]
