# Generated by Django 4.1.1 on 2023-04-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_fedbacktoboo_fedbacktobook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fedbacktobook',
            name='fedback',
        ),
        migrations.AddField(
            model_name='books',
            name='fedback',
            field=models.IntegerField(default=0),
        ),
    ]
