# Generated by Django 4.1.1 on 2023-04-19 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_fedbacktobook_fedback_books_fedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fedbacktobook',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.books'),
        ),
    ]
