# Generated by Django 4.2.1 on 2023-05-30 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_fedbacktobook_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fedbacktobook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books'),
        ),
    ]
